<a href="https://colab.research.google.com/github/Lilyraea/Python-Cleaning-Project/blob/main/Python_Cleaning_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Cleaning a Dataset

# Introduction

This project is about cleaning a dataset programmatically, using Python and its tools and ensuring that the dataset is at an optimum level for use in further analysis or to provide insights.

The data is from an Excel workbook, and contains different tables. It will be split up and saved into individual worksheets in a new workbook as a clean dataset.

# Loading the Dataset

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv(r"/content/Clinic KPIs.csv", header=1)
data

,Month,Total number of chemical sterilzation passed,Total number performed,Sterlization compliance rate,Benchmark,Average/\nMean,Standard \nDeviation,UCL,LCL,Unnamed: 9,...,Unnamed: 29,Month.3,Number reported,Number of patients with minor surgical procedures,Percentage.2,Benchmark.3,Average/\nMean.3,Standard \nDeviation.3,UCL.3,LCL.3
0,24-Jan,1,1,100,100,100.0,0.0,100.0,100.0,NaN,...,NaN,24-Jan,0,0,0,0,0.0,0.0,0.0,0.0
1,24-Feb,11,11,100,100,NaN,NaN,NaN,NaN,NaN,...,NaN,24-Feb,0,0,0,0,NaN,NaN,NaN,NaN
2,24-Mar,4,4,100,100,NaN,NaN,NaN,NaN,NaN,...,NaN,24-Mar,0,0,0,0,NaN,NaN,NaN,NaN
3,24-Apr,7,7,100,100,NaN,NaN,NaN,NaN,NaN,...,NaN,24-Apr,0,0,0,0,NaN,NaN,NaN,NaN
4,24-May,8,8,100,100,NaN,NaN,NaN,NaN,NaN,...,NaN,24-May,0,0,0,0,NaN,NaN,NaN,NaN
5,24-Jun,4,4,100,100,NaN,NaN,NaN,NaN,NaN,...,NaN,24-Jun,0,1,0,0,NaN,NaN,NaN,NaN
6,24-Jul,14,14,100,100,NaN,NaN,NaN,NaN,NaN,...,NaN,24-Jul,0,0,0,0,NaN,NaN,NaN,NaN
7,24-Aug,3,3,100,100,NaN,NaN,NaN,NaN,NaN,...,NaN,24-Aug,0,0,0,0,NaN,NaN,NaN,NaN
8,24-Sep,7,7,100,100,NaN,NaN,NaN,NaN,NaN,...,NaN,24-Sep,0,2,0,0,NaN,NaN,NaN,NaN
9,24-Oct,9,9,100,100,NaN,NaN,NaN,NaN,NaN,...,NaN,24-Oct,0,2,0,0,NaN,NaN,NaN,NaN
10,24-Nov,3,3,100,100,NaN,NaN,NaN,NaN,NaN,...,NaN,24-Nov,0,0,0,0,NaN,NaN,NaN,NaN
11,24-Dec,4,4,100,100,NaN,NaN,NaN,NaN,NaN,...,NaN,24-Dec,0,0,0,0,NaN,NaN,NaN,NaN

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 39 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   Month                                                   12 non-null     object
 1   Total number of chemical sterilzation passed            12 non-null     int64
 2   Total number performed                                  12 non-null     int64
 3   Sterlization compliance rate                            12 non-null     int64
 4   Benchmark                                               12 non-null     int64
 5   Average/
Mean                                           1 non-null      float64
 6   Standard
Deviation                                     1 non-null      float64
 7   UCL                                                     1 non-null      float64
 8   LCL                                                     1 non-null      float64
 9   Unnamed: 9                                              0 non-null      float64
 10  Month.1                                                 12 non-null     object
 11  Number of needlestick injuries                          12 non-null     int64
 12  Number of days in the month                             12 non-null     int64
 13  Percentage                                              12 non-null     float64
 14  Benchmark.1                                             12 non-null     int64
 15  Average/
Mean.1                                         1 non-null      float64
 16  Standard
Deviation.1                                   1 non-null      float64
 17  UCL.1                                                   1 non-null      float64
 18  LCL.1                                                   1 non-null      float64
 19  Unnamed: 19                                             0 non-null      float64
 20  Month.2                                                 12 non-null     object
 21  Number of IM/IV/SC injections site infections reported  12 non-null     int64
 22  Number of patients with IV/SC/IM administered           12 non-null     int64
 23  Percentage.1                                            12 non-null     int64
 24  Benchmark.2                                             12 non-null     int64
 25  Average/
Mean.2                                         1 non-null      float64
 26  Standard
Deviation.2                                   1 non-null      float64
 27  UCL.2                                                   1 non-null      float64
 28  LCL.2                                                   1 non-null      float64
 29  Unnamed: 29                                             0 non-null      float64
 30  Month.3                                                 12 non-null     object
 31  Number reported                                         12 non-null     int64
 32  Number of patients with minor surgical procedures       12 non-null     int64
 33  Percentage.2                                            12 non-null     int64
 34  Benchmark.3                                             12 non-null     int64
 35  Average/
Mean.3                                         1 non-null      float64
 36  Standard
Deviation.3                                   1 non-null      float64
 37  UCL.3                                                   1 non-null      float64
 38  LCL.3                                                   1 non-null      float64
dtypes: float64(20), int64(15), object(4)
memory usage: 3.8+ KB

In [ ]:
data.describe()

,Total number of chemical sterilzation passed,Total number performed,Sterlization compliance rate,Benchmark,Average/\nMean,Standard \nDeviation,UCL,LCL,Unnamed: 9,Number of needlestick injuries,...,LCL.2,Unnamed: 29,Number reported,Number of patients with minor surgical procedures,Percentage.2,Benchmark.3,Average/\nMean.3,Standard \nDeviation.3,UCL.3,LCL.3
count,12.000000,12.000000,12.0,12.0,1.0,1.0,1.0,1.0,0.0,12.000000,...,1.0,0.0,12.0,12.000000,12.0,12.0,1.0,1.0,1.0,1.0
mean,6.250000,6.250000,100.0,100.0,100.0,0.0,100.0,100.0,NaN,0.083333,...,0.0,NaN,0.0,0.416667,0.0,0.0,0.0,0.0,0.0,0.0
std,3.792936,3.792936,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.288675,...,NaN,NaN,0.0,0.792961,0.0,0.0,NaN,NaN,NaN,NaN
min,1.000000,1.000000,100.0,100.0,100.0,0.0,100.0,100.0,NaN,0.000000,...,0.0,NaN,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
25%,3.750000,3.750000,100.0,100.0,100.0,0.0,100.0,100.0,NaN,0.000000,...,0.0,NaN,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
50%,5.500000,5.500000,100.0,100.0,100.0,0.0,100.0,100.0,NaN,0.000000,...,0.0,NaN,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
75%,8.250000,8.250000,100.0,100.0,100.0,0.0,100.0,100.0,NaN,0.000000,...,0.0,NaN,0.0,0.250000,0.0,0.0,0.0,0.0,0.0,0.0
max,14.000000,14.000000,100.0,100.0,100.0,0.0,100.0,100.0,NaN,1.000000,...,0.0,NaN,0.0,2.000000,0.0,0.0,0.0,0.0,0.0,0.0

# Cleaning the Dataset

Looking at the columns that appear in the data, it seems some columns are not enetirely necessary as most of their values are null and the values they even have can be calculated independently based off the available data. So we drop these columns.

In [ ]:
keywords = ['Average/\nMean', 'Standard \nDeviation', 'Percentage', 'LCL', 'UCL']  # These are like your '%...%' patterns

# Join into a single regex pattern
pattern = '|'.join(keywords)  # Result: 'Average|Benchmark|LCL|UCL'

# Drop columns whose names contain any of the keywords
data = data.drop(columns=data.filter(regex=pattern).columns)

data

,Month,Total number of chemical sterilzation passed,Total number performed,Sterlization compliance rate,Benchmark,Unnamed: 9,Month.1,Number of needlestick injuries,Number of days in the month,Benchmark.1,Unnamed: 19,Month.2,Number of IM/IV/SC injections site infections reported,Number of patients with IV/SC/IM administered,Benchmark.2,Unnamed: 29,Month.3,Number reported,Number of patients with minor surgical procedures,Benchmark.3
0,24-Jan,1,1,100,100,NaN,24-Jan,0,31,1,NaN,24-Jan,0,116,0,NaN,24-Jan,0,0,0
1,24-Feb,11,11,100,100,NaN,24-Feb,0,29,1,NaN,24-Feb,0,103,0,NaN,24-Feb,0,0,0
2,24-Mar,4,4,100,100,NaN,24-Mar,0,31,1,NaN,24-Mar,0,107,0,NaN,24-Mar,0,0,0
3,24-Apr,7,7,100,100,NaN,24-Apr,0,30,1,NaN,24-Apr,0,119,0,NaN,24-Apr,0,0,0
4,24-May,8,8,100,100,NaN,24-May,0,31,1,NaN,24-May,0,149,0,NaN,24-May,0,0,0
5,24-Jun,4,4,100,100,NaN,24-Jun,0,30,1,NaN,24-Jun,0,134,0,NaN,24-Jun,0,1,0
6,24-Jul,14,14,100,100,NaN,24-Jul,0,31,1,NaN,24-Jul,0,143,0,NaN,24-Jul,0,0,0
7,24-Aug,3,3,100,100,NaN,24-Aug,0,31,1,NaN,24-Aug,0,140,0,NaN,24-Aug,0,0,0
8,24-Sep,7,7,100,100,NaN,24-Sep,1,30,1,NaN,24-Sep,0,105,0,NaN,24-Sep,0,2,0
9,24-Oct,9,9,100,100,NaN,24-Oct,0,31,1,NaN,24-Oct,0,131,0,NaN,24-Oct,0,2,0
10,24-Nov,3,3,100,100,NaN,24-Nov,0,30,1,NaN,24-Nov,0,130,0,NaN,24-Nov,0,0,0
11,24-Dec,4,4,100,100,NaN,24-Dec,0,31,1,NaN,24-Dec,0,105,0,NaN,24-Dec,0,0,0

After dropping unnecessary columns, I renamed some columns that have suffixes to differentiate columns with the same name. This is because going off how the data looks currently, it seems we have more than one table within the set as they have a similar order and progression of column headers. So we rename them to give them proper headers as we are going to subset the whole table to generate the individual tables found within the set.

In [ ]:
data = data.rename(columns={
    'Month': 'Date',
    'Month.1': 'Date',
    'Month.2': 'Date',
    'Month.3': 'Date',
    'Benchmark.1': 'Benchmark',
    'Benchmark.2': 'Benchmark',
    'Benchmark.3': 'Benchmark'
})
data.columns

Index(['Date', 'Total number of chemical sterilzation passed',
       'Total number performed', 'Sterlization compliance rate', 'Benchmark',
       'Unnamed: 9', 'Date', 'Number of needlestick injuries',
       'Number of days in the month', 'Benchmark', 'Unnamed: 19', 'Date',
       'Number of IM/IV/SC injections site infections reported',
       'Number of patients with IV/SC/IM administered', 'Benchmark',
       'Unnamed: 29', 'Date', 'Number reported',
       'Number of patients with minor surgical procedures', 'Benchmark'],
      dtype='object')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 20 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   Date                                                    12 non-null     object
 1   Total number of chemical sterilzation passed            12 non-null     int64
 2   Total number performed                                  12 non-null     int64
 3   Sterlization compliance rate                            12 non-null     int64
 4   Benchmark                                               12 non-null     int64
 5   Unnamed: 9                                              0 non-null      float64
 6   Date                                                    12 non-null     object
 7   Number of needlestick injuries                          12 non-null     int64
 8   Number of days in the month                             12 non-null     int64
 9   Benchmark                                               12 non-null     int64
 10  Unnamed: 19                                             0 non-null      float64
 11  Date                                                    12 non-null     object
 12  Number of IM/IV/SC injections site infections reported  12 non-null     int64
 13  Number of patients with IV/SC/IM administered           12 non-null     int64
 14  Benchmark                                               12 non-null     int64
 15  Unnamed: 29                                             0 non-null      float64
 16  Date                                                    12 non-null     object
 17  Number reported                                         12 non-null     int64
 18  Number of patients with minor surgical procedures       12 non-null     int64
 19  Benchmark                                               12 non-null     int64
dtypes: float64(3), int64(13), object(4)
memory usage: 2.0+ KB

After renaming, I begin to subset and pull the individual tables from the overall dataset.

In [ ]:
# Table 1: Sterilization (Columns 0–4)
table1 = data.iloc[:, 0:5].dropna(how='all')
table1.head()

,Date,Total number of chemical sterilzation passed,Total number performed,Sterlization compliance rate,Benchmark
0,24-Jan,1,1,100,100
1,24-Feb,11,11,100,100
2,24-Mar,4,4,100,100
3,24-Apr,7,7,100,100
4,24-May,8,8,100,100

In [ ]:
# Table 2: Incidence of Needle Stick Injuries (Columns 10–18)
table2 = data.iloc[:, 6:10].dropna(how='all')
table2.head()

,Date,Number of needlestick injuries,Number of days in the month,Benchmark
0,24-Jan,0,31,1
1,24-Feb,0,29,1
2,24-Mar,0,31,1
3,24-Apr,0,30,1
4,24-May,0,31,1

In [ ]:
# Table 3: Incidence of IM/IV/SC injections site infections (Columns 20–28)
table3 = data.iloc[:, 11:15].dropna(how='all')
table3.head()

,Date,Number of IM/IV/SC injections site infections reported,Number of patients with IV/SC/IM administered,Benchmark
0,24-Jan,0,116,0
1,24-Feb,0,103,0
2,24-Mar,0,107,0
3,24-Apr,0,119,0
4,24-May,0,149,0

In [ ]:
# Table 4: Incidence of Surgical site infections (Columns 30–38)
table4 = data.iloc[:, 16:].dropna(how='all')
table4.head()

,Date,Number reported,Number of patients with minor surgical procedures,Benchmark
0,24-Jan,0,0,0
1,24-Feb,0,0,0
2,24-Mar,0,0,0
3,24-Apr,0,0,0
4,24-May,0,0,0

Correcting the errors in the column names of Table 1 and checking that the data types of all columns are appropriate.

In [ ]:
#To correct the spellings of sterilization in the column headers
table1 = table1.rename(columns={
    'Total number of chemical sterilzation passed': 'Total number of chemical sterilization passed',
    'Sterlization compliance rate': 'Sterilization compliance rate'
})
table1.dtypes

Date                                             object
Total number of chemical sterilization passed     int64
Total number performed                            int64
Sterilization compliance rate                     int64
Benchmark                                         int64
dtype: object

In [ ]:
table2.dtypes

Date                              object
Number of needlestick injuries     int64
Number of days in the month        int64
Benchmark                          int64
dtype: object

In [ ]:
table3.dtypes

Date                                                      object
Number of IM/IV/SC injections site infections reported     int64
Number of patients with IV/SC/IM administered              int64
Benchmark                                                  int64
dtype: object

In [ ]:
table4.dtypes

Date                                                 object
Number reported                                       int64
Number of patients with minor surgical procedures     int64
Benchmark                                             int64
dtype: object

# Exporting to different sheets in the same Excel Workbook

To write the different dataframes to different sheets in the same Excel Workbook, use pd.ExcelWriter

In [ ]:
with pd.ExcelWriter('Cleaning Python Project.xlsx') as writer:
    # Write each DataFrame to a different sheet
    table1.to_excel(writer, sheet_name='Sterilization', index=False)
    table2.to_excel(writer, sheet_name='Needle Stick Injuries', index=False)
    table3.to_excel(writer, sheet_name='Injections site infections', index=False)
    table4.to_excel(writer, sheet_name='Surgical site infections', index=False)

After this, you can check files in the Colab environment and download the workbook to your PC.